from __future__ import annotations

import csv
import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import pandas as pd

from cce_data.adapters import load_examples
from cce_data.download import DEFAULT_CONFIG, default_sources, load_source_config
from cce_data.schema import CANONICAL_COLUMNS, CanonicalExample


def _json_default(value):
    try:
        import numpy as np

        if isinstance(value, np.integer):
            return int(value)
        if isinstance(value, np.floating):
            return float(value)
    except ImportError:
        pass
    return str(value)


def write_jsonl(records: Iterable[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False, default=_json_default) + "\n")


def write_csv(records: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=CANONICAL_COLUMNS)
        writer.writeheader()
        for record in records:
            row = dict(record)
            row["exclusion_reasons"] = json.dumps(row.get("exclusion_reasons", []), ensure_ascii=False)
            row["metadata"] = json.dumps(row.get("metadata", {}), ensure_ascii=False)
            writer.writerow(row)


def dataset_card(manifest: dict) -> str:
    counts = manifest["counts"]
    lines = [
        "# Phase 2 Canonical Dataset",
        "",
        "This dataset is generated by the counterfactual conversation emulation Phase 2 pipeline.",
        "Raw data are not committed to git; rerun the download step to reproduce.",
        "",
        "## Schema",
        "",
        "- `x_patient_context`: patient information available at time zero.",
        "- `a_clinician`: clinician final diagnosis/differential/management-plan action.",
        "- `e_action_repr`: reserved for embeddings/clusters in later phases.",
        "- `y_score`: rubric score, null until judge scoring is run.",
        "- `inclusion_status`: `included`, `excluded`, or `auxiliary_only`.",
        "",
        "## Counts",
        "",
        f"- Total rows: {counts['total']}",
        f"- Included rows: {counts['included']}",
        f"- Excluded rows: {counts['excluded']}",
        f"- Auxiliary-only rows: {counts['auxiliary_only']}",
        "",
        "## Source Counts",
        "",
    ]
    for source, count in sorted(counts["by_source"].items()):
        lines.append(f"- {source}: {count}")
    lines.extend(
        [
            "",
            "## Important Caveat",
            "",
            "`y_score` is a surrogate rubric score. Until `cce-score` is run and calibrated, "
            "the dataset should be used for extraction, support diagnostics, and pipeline "
            "development rather than final causal-effect estimation.",
            "",
        ]
    )
    return "\n".join(lines)


def build_dataset(
    sources: list[str] | None = None,
    raw_dir: Path = Path("data/raw"),
    output_dir: Path = Path("data/processed"),
    config_path: Path = DEFAULT_CONFIG,
    include_excluded: bool = True,
    include_dialog_only: bool = False,
    sample_per_source: int | None = None,
) -> dict:
    config = load_source_config(config_path)
    selected = sources or default_sources(config)
    all_examples: list[CanonicalExample] = []
    warnings: list[str] = []

    for source in selected:
        try:
            examples = load_examples(source, raw_dir, include_dialog_only=include_dialog_only)
        except FileNotFoundError as exc:
            warnings.append(f"{source}: missing raw files ({exc})")
            continue
        if sample_per_source is not None:
            examples = examples[:sample_per_source]
        all_examples.extend(examples)

    if not include_excluded:
        all_examples = [example for example in all_examples if example.inclusion_status == "included"]

    records = [example.to_record() for example in all_examples]
    output_dir.mkdir(parents=True, exist_ok=True)
    write_jsonl(records, output_dir / "phase2_dataset.jsonl")
    write_csv(records, output_dir / "phase2_dataset.csv")

    by_split: dict[str, list[dict]] = defaultdict(list)
    for record in records:
        by_split[str(record["split"])].append(record)
    split_dir = output_dir / "splits"
    for split, split_records in by_split.items():
        write_jsonl(split_records, split_dir / f"{split}.jsonl")

    statuses = Counter(record["inclusion_status"] for record in records)
    source_counts = Counter(record["source"] for record in records)
    manifest = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "sources": selected,
        "raw_dir": str(raw_dir),
        "output_dir": str(output_dir),
        "counts": {
            "total": len(records),
            "included": statuses.get("included", 0),
            "excluded": statuses.get("excluded", 0),
            "auxiliary_only": statuses.get("auxiliary_only", 0),
            "by_source": dict(source_counts),
            "by_status": dict(statuses),
        },
        "warnings": warnings,
        "files": {
            "jsonl": "phase2_dataset.jsonl",
            "csv": "phase2_dataset.csv",
            "splits_dir": "splits",
            "dataset_card": "dataset_card.md",
        },
    }
    (output_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (output_dir / "dataset_card.md").write_text(dataset_card(manifest), encoding="utf-8")

    # A compact QA table is useful on clusters where opening the full CSV is slow.
    qa_rows = []
    for (source, status), count in Counter(
        (record["source"], record["inclusion_status"]) for record in records
    ).items():
        qa_rows.append({"source": source, "inclusion_status": status, "count": count})
    pd.DataFrame(qa_rows).sort_values(["source", "inclusion_status"]).to_csv(
        output_dir / "qa_counts.csv", index=False
    )
    return manifest
